# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

JobApplicant.create([
  { :created_at => nil, :updated_at => nil, :user_id => nil, :position_id => nil }
])



Position.create([
  { :open => true, :created_at => "2011-12-03 19:08:41", :title => "php dev", :updated_at => "2011-12-03 19:08:41", :rate => 1.0, :user_id => 2, :description => "develops php" },
  { :open => true, :created_at => "2011-12-03 19:09:03", :title => "perl dev", :updated_at => "2011-12-03 19:09:03", :rate => 2.0, :user_id => 2, :description => "develops perl" },
  { :open => true, :created_at => "2011-12-03 19:09:18", :title => "ruby dev", :updated_at => "2011-12-03 19:09:18", :rate => 3.0, :user_id => 2, :description => "develops ruby" },
  { :open => true, :created_at => "2011-12-03 19:09:59", :title => "iOS dev", :updated_at => "2011-12-03 19:09:59", :rate => 4.0, :user_id => 1, :description => "writes iOS apps" },
  { :open => true, :created_at => "2011-12-03 19:10:22", :title => "Android Dev", :updated_at => "2011-12-03 19:10:22", :rate => 6.0, :user_id => 1, :description => "Develop Android Apps" },
  { :open => true, :created_at => "2011-12-03 19:10:50", :title => "BlackBerry Dev", :updated_at => "2011-12-03 19:10:50", :rate => 7.0, :user_id => 1, :description => "Develops Blackberry Apps" }
])



Profile.create([
  { :city => nil, :address1 => nil, :created_at => nil, :address2 => nil, :available => nil, :updated_at => nil, :zipcode => nil, :skills => nil, :lastname => nil, :user_id => nil, :phone => nil, :firstname => nil, :jobtitle => nil, :state => nil }
])



User.create([
  { :encrypted_password => "$2a$10$AvaG69ZHdb3xruEZKs36NuS.DVADuhW2z53BfSVEjj5Yfl2FJTMwS", :created_at => "2011-12-03 19:07:46", :last_sign_in_ip => "127.0.0.1", :updated_at => "2011-12-03 19:09:40", :last_sign_in_at => "2011-12-03 19:07:46", :sign_in_count => 2, :reset_password_token => nil, :current_sign_in_ip => "127.0.0.1", :reset_password_sent_at => nil, :remember_created_at => nil, :current_sign_in_at => "2011-12-03 19:09:40", :email => "user1@some.com" },
  { :encrypted_password => "$2a$10$qaqHJK3O8fQoOJnmr.cxwOvoBtb9lFfBPYI9PHqTlbqrF5EQwFt9K", :created_at => "2011-12-03 19:08:06", :last_sign_in_ip => "127.0.0.1", :updated_at => "2011-12-03 19:08:06", :last_sign_in_at => "2011-12-03 19:08:06", :sign_in_count => 1, :reset_password_token => nil, :current_sign_in_ip => "127.0.0.1", :reset_password_sent_at => nil, :remember_created_at => nil, :current_sign_in_at => "2011-12-03 19:08:06", :email => "user2@some.com" }
])


